pose_classification: 
  actions: ['flute', 'violin', 'trumpet', 'saxophone', 'no action']
  sequence_length: 30
  latency_factor: 2 

files: 
  model_path: "source/pose/final_model.h5"
  audio: 'source/audio_resources/'
  img: 'source/images/'


morphing:
  loops: 1000
  model_names: ['Flute', 'Violin', 'Trumpet', 'Tenor_Saxophone']


controller: 
  sr: 44100
  messages: ['Start Rec', 'Stop Rec', 'Play', 'Pause', 'Clear']
  max_duration: 14
